repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: double-quote-string-fixer
      - id: check-toml
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.11.4
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [ --max-line-length=120 ]
        additional_dependencies: [
          flake8-bugbear,
          flake8-alfred,
          flake8-comprehensions,
          flake8-mutable,
          flake8-print,
          flake8-simplify,
          flake8-encodings,
          flake8-pytest-style,
          flake8-builtins,
          flake8-cognitive-complexity,
          flake8-comprehensions,
          flake8-expression-complexity,
          flake8-functions,
          flake8-string-format,
          flake8-quotes,
          flake8-warnings,
          flake8-use-pathlib,
          flake8-fixme,
        ]
        exclude: "todolist/[a-zA-Z]*/(migrations)/(.)*"
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ '-iii', '-ll' ]
