name: Build

on:
  push:
    branches-ignore:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone code
        uses: actions/checkout@v2
      - name: docker build
        run: docker build -t alex85doronin/to_do_list:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: docker push
        run: docker push alex85doronin/to_do_list:$GITHUB_REF_NAME-$GITHUB_RUN_ID
      - name: docker push
        run: docker push alex85doronin/to_do_list:latest
